// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobufferclient.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Client {

  /// <summary>Holder for reflection information generated from protobufferclient.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ProtobufferclientReflection {

    #region Descriptor
    /// <summary>File descriptor for protobufferclient.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtobufferclientReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdwcm90b2J1ZmZlcmNsaWVudC5wcm90bxIRcHJvdG9idWZmZXJjbGllbnQi",
            "IwoLY29tbXVuaWNhdGUSFAoMcHJvdG9tZXNzYWdlGAEgASgJQgmqAgZDbGll",
            "bnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedCodeInfo(null, new pbr::GeneratedCodeInfo[] {
            new pbr::GeneratedCodeInfo(typeof(global::Client.communicate), global::Client.communicate.Parser, new[]{ "Protomessage" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class communicate : pb::IMessage<communicate> {
    private static readonly pb::MessageParser<communicate> _parser = new pb::MessageParser<communicate>(() => new communicate());
    public static pb::MessageParser<communicate> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Client.ProtobufferclientReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public communicate() {
      OnConstruction();
    }

    partial void OnConstruction();

    public communicate(communicate other) : this() {
      protomessage_ = other.protomessage_;
    }

    public communicate Clone() {
      return new communicate(this);
    }

    /// <summary>Field number for the "protomessage" field.</summary>
    public const int ProtomessageFieldNumber = 1;
    private string protomessage_ = "";
    public string Protomessage {
      get { return protomessage_; }
      set {
        protomessage_ = pb::Preconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as communicate);
    }

    public bool Equals(communicate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Protomessage != other.Protomessage) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Protomessage.Length != 0) hash ^= Protomessage.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Protomessage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Protomessage);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Protomessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Protomessage);
      }
      return size;
    }

    public void MergeFrom(communicate other) {
      if (other == null) {
        return;
      }
      if (other.Protomessage.Length != 0) {
        Protomessage = other.Protomessage;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Protomessage = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
